LojaDeCarros/Models/Carro.cs
using System.ComponentModel.DataAnnotations;

namespace LojaDeCarros.Models
{
    public class Carro
    {
        public int Id { get; set; }
        
        [Required]
        public string Modelo { get; set; }
        
        [Required]
        [Range(1950, 2024, ErrorMessage = "O ano de fabricação deve estar entre 1900 e 2024.")]
        public int AnoFabricacao { get; set; }

        [Required]
        public string Chassi { get; set; }

        [Required]
        [Range(typeof(decimal), "1,00", "79999999,99", ErrorMessage = "O preço deve ser maior que 0.1.")]
        public decimal Preco { get; set; }
    }
}

LojaDeCarros/Models/ErrorViewModel.cs
namespace LojaDeCarros.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LojaDeCarros/Controllers/CarrosController.cs
using LojaDeCarros.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using LojaDeCarros.Models;

namespace LojaDeCarros.Controllers
{
    public class CarrosController : Controller
    {
        private readonly AppDbContext _context;

        public CarrosController (AppDbContext context)
        {
            _context = context;
        }

        // GET: HomeController1
        public async Task<ActionResult> Index()
        {
            var carros = await _context.Carros.ToListAsync();
            return View(carros);
        }

        // GET: HomeController1/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: HomeController1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomeController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Carro carro)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Carros.Add(carro);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController1/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var carro = await _context.Carros.FindAsync(id);
            if (carro == null)
            {
                return NotFound();
            }

            return View(carro);
        }

        // POST: HomeController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Modelo,AnoModelo,Chassi,Preco")] Carro carro)
        {
            if (id != carro.Id) {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                return View(carro);
            }

            try
            {
                _context.Update(carro);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CarroExists(carro.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToAction(nameof(Index));
        }
        private bool CarroExists(int id)
        {
            return _context.Carros.Any(e => e.Id == id);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var carro = await _context.Carros.FindAsync(id);

            if (carro == null)
            {
                return NotFound();
            }

            return View(carro);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var carro = _context.Carros.Find(id);

            _context.Carros.Remove(carro);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

LojaDeCarros/Controllers/HomeController.cs
using System.Diagnostics;
using LojaDeCarros.Models;
using Microsoft.AspNetCore.Mvc;

namespace LojaDeCarros.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LojaDeCarros/Views/Carros/Create.cshtml
@model LojaDeCarros.Models.Carro

<h1>Cadastrar Carro</h1>

<form asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="Modelo"></label>
        <input asp-for="Modelo" class="form-control" />
        <span asp-validation-for="Modelo" class="text-danger"></span>
    </div>

@*     <div class="form-group">
        <label asp-for="Marca"></label>
        <input asp-for="Marca" class="form-control" />
        <span asp-validation-for="Marca" class="text-danger"></span>
    </div> *@

    <div class="form-group">
        <label asp-for="AnoFabricacao"></label>
        <input asp-for="AnoFabricacao" class="form-control" type="number" />
        <span asp-validation-for="AnoFabricacao" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Chassi"></label>
        <input asp-for="Chassi" class="form-control" />
        <span asp-validation-for="Chassi" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Preco"></label>
        <input asp-for="Preco" class="form-control" type="number" step="0.01" />
        <span asp-validation-for="Preco" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

LojaDeCarros/Views/Carros/Delete.cshtml
@model LojaDeCarros.Models.Carro

<h3>Carro #@Model.Id - @Model.Modelo</h3>

<form asp-action="DeleteConfirmed" asp-route-id="@Model.Id" method="post">
    @Html.AntiForgeryToken()
    <input type="submit" value="Confirmar Exclusão" class="btn btn-danger" />
    <a asp-action="Index">Voltar para a listagem</a>
</form>

LojaDeCarros/Views/Carros/Edit.cshtml
@model LojaDeCarros.Models.Carro

<h1>Editar Carro</h1>

<form asp-action="Edit" asp-route-id="@Model.Id"  method="post">
    @Html.AntiForgeryToken()
    <input name="_HttpMethod" type="hidden" value="PUT" />
    <input asp-for="Id" type="hidden" />

    <div class="form-group">
        <label asp-for="Modelo"></label>
        <input asp-for="Modelo" class="form-control" />
        <span asp-validation-for="Modelo" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="AnoFabricacao"></label>
        <input asp-for="AnoFabricacao" class="form-control" type="number" />
        <span asp-validation-for="AnoFabricacao" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Chassi"></label>
        <input asp-for="Chassi" class="form-control" />
        <span asp-validation-for="Chassi" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Preco"></label>
        <input asp-for="Preco" class="form-control" type="number" step="0.01" />
        <span asp-validation-for="Preco" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

LojaDeCarros/Views/Carros/Index.cshtml
@model IEnumerable<LojaDeCarros.Models.Carro>

<h1>Lista de Carros</h1>

<a asp-action="Create" class="btn btn-success">Cadastrar Carro</a>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Modelo</th>
            <th>Preço</th>
            <td></td>
        </tr>
    </thead>
    <tbody>
        @foreach (var carro in Model)
        {
            <tr>
                <td>@carro.Id</td>
                <td>@carro.Modelo</td>
                <td>@carro.Preco.ToString("C")</td>
                <td><a asp-action="Edit" asp-route-id="@carro.Id">Editar</a><a asp-action="Delete" class="btn btn-danger" asp-route-id="@carro.Id">Remover</a></td>
            </tr>
        }
    </tbody>
</table>

LojaDeCarros/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem-vindo!</h1>
    <a asp-controller="Carros" asp-action="Index">Carros</a>
</div>

LojaDeCarros/Views/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

LojaDeCarros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LojaDeCarros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LojaDeCarros.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LojaDeCarros</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - LojaDeCarros - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>